# use this to install in casa os
version: '3.8'

services:
  app:
    container_name: Argus
    image: 9919952021/argus:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1920:8080"
    restart: always

# to build the image
# docker build -t 9919952021/argus:latest .

# to login to docker hub
# docker login

# to push the image
# docker push 9919952021/argus:latest